{
 "title": "Postgres metrics dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Commits by day and users (with time picker)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    DATE_TRUNC('day', commit_date) AS day,\r\n    SUM(CASE WHEN login = 'user235' THEN changed_lines ELSE 0 END) AS user235,\r\n    SUM(CASE WHEN login = 'user2' THEN changed_lines ELSE 0 END) AS user2,\r\n    SUM(CASE WHEN login = 'pevgen' THEN changed_lines ELSE 0 END) AS pevgen\r\nFROM git_commits\r\nWHERE DATE_TRUNC('day', commit_date) BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY day\r\nORDER BY day;"
    }
   ]
  },
  {
   "title": "Task times",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT task_id,cycle_time,lead_time FROM task_metrics "
    }
   ]
  },
  {
   "title": "Git commits by user",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select g.login, sum(g.changed_lines) changes\r\nfrom git_commits g\r\ngroup by g.login;"
    }
   ]
  }
 ]
}