{
 "title": "Postgres metrics dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Avearage sp/hour for total sp",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  v.\"Custom_field_Release\" AS release,\r\n  sum(v.total_estimate)/sum(v.\"Hours\") AS sp_total_estimate \r\nFROM view_tasks_hours_sp v\r\nGROUP BY v.\"Custom_field_Release\"\r\nORDER BY v.\"Custom_field_Release\""
    }
   ]
  },
  {
   "title": "Average max sp/hour",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(v.max_estimate)/sum(v.\"Hours\") as sp_all\r\nfrom view_tasks_hours_sp v"
    }
   ]
  },
  {
   "title": "Average total sp/hour",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(v.total_estimate)/sum(v.\"Hours\") as sp\r\nfrom view_tasks_hours_sp v"
    }
   ]
  },
  {
   "title": "Task times",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT task_id,cycle_time,lead_time FROM task_metrics "
    }
   ]
  },
  {
   "title": "Git commits by user",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 14 },
   "targets": [
    {
     "rawSql": "select g.login, sum(g.changed_lines) changes\r\nfrom git_commits g\r\ngroup by g.login;"
    }
   ]
  },
  {
   "title": "Commits by day and users (with time picker)",
   "type": "barchart",
   "gridPos": { "h": 1, "w": 7, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    DATE_TRUNC('day', commit_date) AS day,\r\n    SUM(CASE WHEN login = 'user235' THEN changed_lines ELSE 0 END) AS user235,\r\n    SUM(CASE WHEN login = 'user2' THEN changed_lines ELSE 0 END) AS user2,\r\n    SUM(CASE WHEN login = 'pevgen' THEN changed_lines ELSE 0 END) AS pevgen\r\nFROM git_commits\r\nWHERE DATE_TRUNC('day', commit_date) BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY day\r\nORDER BY day;"
    }
   ]
  }
 ]
}